# Generated by Django 4.1.2 on 2024-06-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_mecanico_imagen_alter_mecanico_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mecanicos'),
        ),
    ]
