# Generated by Django 4.1.2 on 2024-06-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mecanico',
            fields=[
                ('id_mecanico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('experiencia', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
    ]
