# Generated by Django 4.1.2 on 2024-06-11 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecanico',
            name='estado',
        ),
    ]
