# Generated by Django 4.1.2 on 2024-06-14 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_mecanico_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id_name', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('direccion', models.CharField(max_length=50)),
                ('sucursal', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='fecha_ingreso',
        ),
        migrations.AddField(
            model_name='mecanico',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AddField(
            model_name='mecanico',
            name='sucursal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
