# Generated by Django 5.0.3 on 2024-06-24 13:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mecanico',
            fields=[
                ('id_mecanico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('correo', models.CharField(max_length=50)),
                ('sucursal', models.CharField(blank=True, max_length=50, null=True)),
                ('especialidad', models.CharField(max_length=50)),
                ('experiencia', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mecanicos')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id_name', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('direccion', models.CharField(max_length=50)),
                ('sucursal', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios')),
            ],
        ),
        migrations.CreateModel(
            name='clienteUser',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=50)),
                ('id_unico', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50, null=True)),
                ('patente', models.CharField(max_length=50, null=True)),
                ('comentario', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_en_el_momento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_añadido', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_usuario', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_servicio', to='base.servicio')),
            ],
        ),
        migrations.AddConstraint(
            model_name='carrito',
            constraint=models.UniqueConstraint(fields=('patente', 'servicio'), name='unique_patente_servicio'),
        ),
    ]
