# Generated by Django 4.1.2 on 2024-06-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_mecanico_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='telefono',
            field=models.IntegerField(max_length=50),
        ),
    ]
