# Generated by Django 5.0.6 on 2024-06-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_cliente_servicio_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='precio',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
