# Generated by Django 5.0.6 on 2024-06-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_cliente_direccion_cliente_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='patente',
        ),
        migrations.AddField(
            model_name='cita',
            name='marca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='patente',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
