# Generated by Django 5.0.3 on 2024-06-20 22:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_cita_cliente_alter_cita_hora_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='clienteUser',
        ),
    ]
